sudo: required
services:
  - docker

before_install:
  - docker build -t sahil070197/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sahil070197/react-test npm test

after_success:
  - docker build -t sahil070197/multi-client ./client
  - docker build -t sahil070197/multi-nginx ./nginx
  - docker build -t sahil070197/multi-server ./server
  - docker build -t sahil070197/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  
  - docker push sahil070197/multi-nginx
  - docker push sahil070197/multi-server
  - docker push sahil070197/multi-worker
  - docker push sahil070197/multi-client
